SELECT ALBCODIGO, ALBNOME, ARTNOME, BDSNOME
  FROM ALBUNS
  LEFT JOIN ARTISTAS ON ALBARTISTA = ARTCODIGO
  LEFT JOIN BANDAS ON ALBBANDA = BDSCODIGO;
  
SELECT ALBCODIGO, ALBNOME, IFNULL(ARTNOME, BDSNOME) INTERPRETE
  FROM ALBUNS
  LEFT JOIN ARTISTAS ON ALBARTISTA = ARTCODIGO
  LEFT JOIN BANDAS ON ALBBANDA = BDSCODIGO;
  
SELECT COUNT(ALBNOME) QUANTIDADE, IFNULL(ARTNOME, BDSNOME) INTERPRETE
  FROM ALBUNS
  LEFT JOIN ARTISTAS ON ALBARTISTA = ARTCODIGO
  LEFT JOIN BANDAS ON ALBBANDA = BDSCODIGO
  GROUP BY IFNULL(ARTNOME, BDSNOME)
  ORDER BY QUANTIDADE, INTERPRETE;
  
SELECT IFNULL(ARTNOME, BDSNOME) INTERPRETE, COUNT(ALBNOME) QTDE, GROUP_CONCAT(ALBNOME)
  FROM ALBUNS
  LEFT JOIN ARTISTAS ON ALBARTISTA = ARTCODIGO
  LEFT JOIN BANDAS ON ALBBANDA = BDSCODIGO
  GROUP BY IFNULL(ARTNOME, BDSNOME)
  ORDER BY QTDE, INTERPRETE;
  
SELECT ALBNOME, GROUP_CONCAT(MSCNOME)
FROM ALBUNS
INNER JOIN FAIXAS ON FXSALBUM = ALBCODIGO
INNER JOIN MUSICAS ON MSCCODIGO = FXSMUSICA
GROUP BY ALBNOME;

SELECT ALBNOME, time_format(SEC_TO_TIME(SUM(TIME_TO_SEC(MSCDURACAO))),'%H:%i:%s')  Tempo
FROM ALBUNS
INNER JOIN FAIXAS ON FXSALBUM = ALBCODIGO
INNER JOIN MUSICAS ON MSCCODIGO = FXSMUSICA
GROUP BY ALBNOME;



select * from musicas;
select * from faixas WHERE FXSALBUM = 57;