/*Lista todos os álbuns, e seus respectivos autores*/
SELECT ALBCODIGO 'Código do Álbum', ALBNOME 'Nome do Álbum', ARTNOME 'Artista', BDSNOME 'Banda'
FROM ALBUNS
LEFT JOIN ARTISTAS ON ALBARTISTA = ARTCODIGO
LEFT JOIN BANDAS ON ALBBANDA = BDSCODIGO;
  
/*Lista todos os álbuns, e seus respectivos autores, porém sem listar campos nulos*/
SELECT ALBCODIGO 'Código do Álbum', ALBNOME 'Nome do Álbum', IFNULL(ARTNOME, BDSNOME) 'Interprete'
FROM ALBUNS
LEFT JOIN ARTISTAS ON ALBARTISTA = ARTCODIGO
LEFT JOIN BANDAS ON ALBBANDA = BDSCODIGO;
  
/*Lista a quantidade de álbuns dos interpretes*/
SELECT COUNT(ALBNOME) 'Quantidade de Álbuns', IFNULL(ARTNOME, BDSNOME) 'Interprete'
FROM ALBUNS
LEFT JOIN ARTISTAS ON ALBARTISTA = ARTCODIGO
LEFT JOIN BANDAS ON ALBBANDA = BDSCODIGO
GROUP BY IFNULL(ARTNOME, BDSNOME)
ORDER BY QUANTIDADE, INTERPRETE;
  
/*Lista todos os álbuns, quantidade e nome das musicas*/
SELECT IFNULL(ARTNOME, BDSNOME) 'Interprete', GROUP_CONCAT(ALBNOME) 'Músicas', COUNT(ALBNOME) 'Quantidade de Músicas'
FROM ALBUNS
LEFT JOIN ARTISTAS ON ALBARTISTA = ARTCODIGO
LEFT JOIN BANDAS ON ALBBANDA = BDSCODIGO
GROUP BY IFNULL(ARTNOME, BDSNOME)
ORDER BY QTDE, INTERPRETE;
  
/*Lista todos os álbuns e suas respectivas músicas*/
SELECT ALBNOME 'Nome do Álbum', GROUP_CONCAT(MSCNOME) 'Músicas'
FROM ALBUNS
INNER JOIN FAIXAS ON FXSALBUM = ALBCODIGO
INNER JOIN MUSICAS ON MSCCODIGO = FXSMUSICA
GROUP BY ALBNOME;

/*Lista todos os álbuns, e o tempo total de reprodução*/
SELECT ALBNOME 'Nome do Álbum', time_format(SEC_TO_TIME(SUM(TIME_TO_SEC(MSCDURACAO))),'%H:%i:%s') 'Tempo Total de Reprodução'
FROM ALBUNS
INNER JOIN FAIXAS ON FXSALBUM = ALBCODIGO
INNER JOIN MUSICAS ON MSCCODIGO = FXSMUSICA
GROUP BY ALBNOME;